name: svelte_workspace
description: SvelteDart workspace.
version: 1.0.6
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0

workspace:
  - svelte
  - svelte_ast
  # - svelte_builder
  - svelte_runtime

  # - svelte_examples
