name: piko
description: Dart web framework.
version: 1.0.0-dev.61
homepage: https://piko.ykmnkmi.dev

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.4.0

dev_dependencies:
  lints: ^1.0.1
