name: ng
description: Angular template syntax & Vue/Svelte like components.
version: 1.0.0-dev.5
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  analyzer: ^1.7.2
  angular_ast: ^1.0.0
  expression: ^1.0.0-dev
  meta: ^1.6.0
  piko: ^1.0.0-dev

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
  stack_trace: ^1.10.0

dependency_overrides:
  angular_ast:
    git:
      path: angular_ast
      ref: google
      url: https://github.com/angulardart/angular
  expression:
    path: ../expression
  piko:
    path: ../..
