name: svelte_ast
description: Parser and utilities for SvelteDart template compiler.
version: 1.0.0-27.beta
repository: https://github.com/ykmnkmi/svelte.dart

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  _fe_analyzer_shared: ^92.0.0
  analyzer: ^9.0.0
  csslib: ^1.0.2
  logging: ^1.3.0
  meta: ^1.17.0
  pub_semver: ^2.2.0
  source_span: ^1.10.1

dev_dependencies:
  collection: ^1.19.1
  lints: ^6.0.0
  stack_trace: ^1.12.1
  test: ^1.28.0
