name: svelte
description: SvelteDart.
version: 1.0.0-dev.4
repository: https://github.com/ykmnkmi/svelte.dart

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  svelte_runtime: ^1.0.0-dev.18
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
