name: svelte_examples
description: SvelteDart examples.
version: 1.0.0-dev.16
repository: https://github.com/ykmnkmi/svelte.dart
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  markdown: ^7.3.0
  meta: ^1.17.0
  svelte: ^1.0.0-dev.4
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.3.0
  lints: ^6.0.0
