name: svelte_builder
description: SvelteDart Builder.
version: 1.0.0-dev.6
repository: https://github.com/ykmnkmi/svelte.dart

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^9.0.0
  build: ^4.0.2
  dart_style: ^3.1.2
  logging: ^1.3.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  source_span: ^1.10.1
  svelte_ast: ^1.0.0-27.beta

dev_dependencies:
  build_test: ^3.5.0
  glob: null
  lints: ^6.0.0
  package_config: null
  stack_trace: ^1.12.1
  test: ^1.28.0
